name: app_environment
channels:
  - snowflake
dependencies:
  - claude-agent-sdk=0.1.45
  - plotly=6.6.0
  - pypdf2=3.0.1
  - pypdfium2=4.19.0
  - python=3.11.*
  - reportlab=4.4.9
  - snowflake-snowpark-python=1.48.0
  - statsmodels=0.14.6
  - streamlit=1.52.2
  - streamlit-navigation-bar=3.3.0
  - streamlit-pdf=2.0.0
